// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QTKhachSan.Domain.EF;

#nullable disable

namespace QTKhachSan.Domain.Migrations
{
    [DbContext(typeof(QTKhachSanDb))]
    partial class QTKhachSanDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QTKhachSan.Domain.Entity.DichVu", b =>
                {
                    b.Property<int>("MaLoaiDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiDichVu"), 1L, 1);

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("50");

                    b.HasKey("MaLoaiDichVu");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("QTKhachSan.Domain.Entity.LoaiPhong", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Gia")
                        .HasColumnType("real");

                    b.Property<string>("tenLoaiPhong")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("50");

                    b.HasKey("MaLoai");

                    b.HasIndex("tenLoaiPhong")
                        .IsUnique();

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("QTKhachSan.Domain.Entity.PhieuDatPhong", b =>
                {
                    b.Property<int>("IdPhieuDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhieuDat"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("150");

                    b.Property<int>("IdPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("10");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("50");

                    b.HasKey("IdPhieuDat");

                    b.HasIndex("IdPhong");

                    b.ToTable("PhieuDatPhong", (string)null);
                });

            modelBuilder.Entity("QTKhachSan.Domain.Entity.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"), 1L, 1);

                    b.Property<string>("IdLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("50");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaPhong");

                    b.HasIndex("IdLoai");

                    b.HasIndex("MaPhong");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("QTKhachSan.Domain.Entity.PhieuDatPhong", b =>
                {
                    b.HasOne("QTKhachSan.Domain.Entity.Phong", "Phong")
                        .WithMany("PDatPhong")
                        .HasForeignKey("IdPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QTKhachSan.Domain.Entity.Phong", b =>
                {
                    b.HasOne("QTKhachSan.Domain.Entity.LoaiPhong", "Loai")
                        .WithMany("Phongs")
                        .HasForeignKey("IdLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loai");
                });

            modelBuilder.Entity("QTKhachSan.Domain.Entity.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QTKhachSan.Domain.Entity.Phong", b =>
                {
                    b.Navigation("PDatPhong");
                });
#pragma warning restore 612, 618
        }
    }
}
